[package]
name = "kilogoge"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
dotenv = "0.15.0"
kilonova = { path = "../kilonova" }
poise = "0.6.1"
sqlite = "0.36.1"
tokio = { version = "1.43.0", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
